version: "3.8"
services:
  dlk_bot:
    build: .
    container_name: dlk_radio_bot
    restart: unless-stopped
    environment:
      # Pass env vars by reference from host or override here.
      - API_ID
      - API_HASH
      - BOT_TOKEN
      - ASSISTANT_SESSION
      - OWNER_ID
      - MONGO_URI
      - MONGO_DBNAME
      - LOG_CHANNEL_ID
    volumes:
      - .:/app
